name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SELECTEL_HOST }}
          username: ${{ secrets.SELECTEL_USERNAME }}
          key: ${{ secrets.SELECTEL_SSH_KEY }}
          script: |
            # Проверяем текущую директорию
            pwd
            ls -la
            
            # Переходим в директорию проекта
            cd /opt/shop-api || exit 1
            
            # Проверяем статус git
            git status
            git pull || exit 1
            
            # Применяем миграции
            psql -U postgres -d shop_api -f migrations/001_init.sql || exit 1
            
            # Собираем приложение
            go build -o shop-api cmd/main.go || exit 1
            
            # Перезапускаем сервис
            sudo systemctl stop shop-api || exit 1
            sudo systemctl start shop-api || exit 1
            
            # Проверяем статус
            sudo systemctl status shop-api || exit 1
            
            # Ждем 5 секунд, пока сервис запустится
            sleep 5
            
            # Проверяем, что сервис работает на IP сервера
            curl -I http://91.105.199.172:8080/api/products || exit 1
            
            # Проверяем Swagger
            curl -I http://91.105.199.172:8080/swagger/index.html || exit 1