name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: 91.105.199.172
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/opt/shop-api"

    - name: Execute deploy commands
      uses: appleboy/ssh-action@master
      with:
        host: 91.105.199.172
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/shop-api
          
          # Backup DB
          PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} pg_dump -h localhost -U postgres shop > backup_$(date +%Y%m%d_%H%M%S).sql
          
          # Apply migrations
          PGPASSWORD=${{ secrets.POSTGRES_PASSWORD }} psql -h localhost -U postgres -d shop -f migrations/001_init.sql
          
          # Build
          go build -o shop-api cmd/main.go
          
          # Restart service
          sudo systemctl restart shop-api
          
          # Check service status
          sudo systemctl status shop-api