name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SELECTEL_HOST }}
          username: ${{ secrets.SELECTEL_USERNAME }}
          key: ${{ secrets.SELECTEL_SSH_KEY }}
          script: |
            cd /opt/shop-api
            git pull
            go build -o shop-api cmd/main.go
            sudo systemctl restart shop-api
            sudo systemctl status shop-api